### PR TITLE
Fset 1630

### PR DESCRIPTION
**Pull request by andrewrembrandt**
Hi Ben & Kevin,

As discussed this is the pull request for the add sifter schemes jira - reviewed yesterday with Ben - I incorporated the feedback we discussed (unfortunately the few handwritten notes were left on my desk, so will pick those up on Monday, and of course tests).

Contactable on email/phone today (will be hanging on the side of a cliff however, so email preferred ;)

Many Thanks,

Andrew

### CODE REVIEW

**Comment by andrewrembrandt** [comment]
Gents, apologies, sbt isn't running integration tests for me properly - will resolve this tonight/weekend

**Comment by andrewrembrandt** [comment]
Hi Ian/Ben - ready for review

**Comment by kjharkin** [comment]
cool - I'l pick this up for review

**Comment by henricook** [comment]
@andrewrembrandt would you mind adding the title of the ticket to the PR title? Or a brief description? It makes it easier to find a change if we need to look back through old PRs. Since we don't squash PRs this can often be the fastest way of finding a changeset

**Comment by kjharkin** [comment]
Looks good - will merge once frontend reviewed

**Pull request merged**
