### PR TITLE
Draft export schema

### PR DESCRIPTION
**Pull request by ollyw**
This version of the export schema is the one discussed as per 17th November. It is a WIP

### CODE REVIEW

**Comment by ollyw** [comment]
@kjharkin do you mind taking a quick look at this?

**Comment by kjharkin** [comment]
Not at all - will take a look

**Comment by rcaller** [comment]
Looks pretty reasonable, a couple of thoughts.  1) do we need a comment on the degree types to make it easier to understand what the data will mean.  2) Any change in the wording of the questions will potentially break the export/import, are we OK with this?

**Comment by kjharkin** [comment]
There are issues with the following which I relayed to Olly yesterday:

"What is your gender identity?"
"What is your sexual orientation?"
"Did you live in the UK between the ages of 14 and 18?"
"Between the ages of 11 to 16, in which school did you spend most of your
education?"
"Between the ages of 16 to 18, in which school did you spend most of your
education?"
"During your school years, were you at any time eligible for free school
meals?"
"Do you have a parent or guardian that has completed a university degree
course or equivalent?"
"When you were 14, what kind of work did your highest-earning parent or
guardian do?
"Did they work as an employee or were they self-employed?"
Which size would best describe their place of work?
Did they supervise employees?

"results": {
         "type": "object",
         "properties": {
           "passed-schemes": {
             "type": "array",
             "uniqueItems": true,
             "minItems": 1,
             "items": {
               "type": "string",
               "minLength": 1,
               "maxLength": 64,
               "enum": [
                 "CentralDepartments",


"assistance-details": {
         "type": "object",
         "properties": {
           "hasDisability": {
             "type": "string",
             "minLength": 2,
             "maxLength": 3


Missing "Adjustments"

**Comment by henricook** [comment]
There's a .DS_Store file in this commit that needs to be removed

**Pull request merged**
